name:                exchange
version:             0.1.0.0
github:              "ntruong/exchange"
license:             BSD3
author:              "Nicholas Truong"
maintainer:          "nt31415@gmail.com"
copyright:           "2018 Nicholas Truong"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ntruong/exchange#readme>

dependencies:
- base           >= 4.7 && < 5
- bytestring     >= 0.10
- containers     >= 0.5
- http-types     >= 0.7
- numeric-limits >= 0.1
- wai            >= 3.2
- wai-app-static >= 3.0
- wai-extra      >= 3.0
- warp           >= 3.2

library:
  source-dirs: src

executables:
  Exchange:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - exchange

tests:
  exchange-test:
    main:                Exchange/Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - exchange
